language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t udayveer27/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true udayveer27/multi-docker npm test
after_success:
  - docker build -t udayveer27/multi-client ./client
  - docker build -t udayveer27/multi-server ./server
  - docker build -t udayveer27/multi-nginx ./nginx
  - docker build -t udayveer27/multi-worker ./worker
  # login to Docker CLI
  -  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push udayveer27/multi-client
  - docker push udayveer27/multi-server
  - docker push udayveer27/multi-nginx
  - docker push udayveer27/multi-worker
