language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t udayveer27/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true udayveer27/multi-docker npm test
after_success:
  - docker build -t udayveer27/multi-client ./client
  - docker build -t udayveer27/multi-server ./server
  - docker build -t udayveer27/multi-nginx ./nginx
  - docker build -t udayveer27/multi-worker ./worker
  # login to Docker CLI
  -  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push udayveer27/multi-client
  - docker push udayveer27/multi-server
  - docker push udayveer27/multi-nginx
  - docker push udayveer27/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "UdayBeanstalk"
  env: "multidocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-682426607174"
  bucket_path: "multidocker-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
